
-- 2 Insere os itens na tabela de Produtos

INSERT INTO Produto (nome, descricao, preco, estoque) VALUES
('X-Burguer', 'Pão, maionese caseira, hambúrger artesanal 180g e queijo prato', 29.00, 30),
('X-Bacon', 'Pão, maionese caseira, hambúrguer artesanal 180g, queijo prato e bacon', 35.00, 25),
('X-Salada', 'Pão, maionese caseira, hambúrguer artesanal 180g, queijo prato, alface e tomate', 33.00, 25),
('Frango Caipira', 'Pão, maionese caseira, sobrecoxa desossada, cream cheese, alface e tomate', 35.00, 20),
('Cheddar', 'Pão, maionese caseira, hambúrguer artesanal 180g, cheddar fundido, bacon e cebola caramelizada', 43.00, 30),
('X-Linguiça', 'Pão francês, maionese caseira, linguiça bragantina, queijo prato e vinagrete', 30.00, 20),
('X-Linguiça Bacon', 'Pão francês, maionese caseira, linguiça bragantina, queijo prato, bacon e vinagrete', 35.00, 20),
('Costelão', 'Pão, maionese caseira, costela bovina desfiada, cebelo caramelizada na cerveja, queijo cheddar', 45.00, 20),
('O Brabo', 'Pão, maionese caseira, hambúguer de picanha bovina 200g, queijo prato, cebola roxa e molho barbecue caseiro', 45.00, 15),
('Infantil', 'Pão, hambúguer artesanal 100g, queijo prato', 15.00, 30),
('Batata-Frita', 'Batata frita', 10.00, 30),
('Batata Rústica com Bacon', 'Batata rústica com bacon', 15.00, 30),
('Batata Rústica com Cheddar', 'Batata rústica com cheddar', 15.00, 30),
('Batata Rústica com Cheddar e Bacon e Cebola Caramelizada', 'Batata rústica com cheddar, bacon e cebola caramelizada', 25.00, 30),
('Coca-Cola', 'Refrigerante de cola', 5.00, 30),
('Coca-Cola Zero', 'Refrigerante de cola zero', 5.00, 30),
('Fanta', 'Refrigerante de laranja', 5.00, 30),
('Fanta Uva', 'Refrigerante de uva', 5.00, 30),
('Guaraná Antártica', 'Refrigerante de guaraná', 5.00, 30),
('Água com Gás', 'Água com gás', 2.00, 30),
('Água sem Gás', 'Água sem gás', 2.00, 30),
('Suco Natural de Laranja', 'Suco natural de laranja', 5.00, 30),
('Suco Natural de Abacaxi', 'Suco natural de abacaxi', 5.00, 30),
('Suco Natural de Maracujá', 'Suco natural de maracujá', 5.00, 30),
('Suco Natural de Melancia', 'Suco natural de melancia', 5.00, 30),
('Suco Natural de Manga', 'Suco natural de manga', 5.00, 30);